---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-configmap
  namespace: movies
  labels:
    app: movies-api
data:
  SqlServerConnectionString: "Server=mssql-service;Database=MOVIES_DOCKER;User Id=sa;Password=x2yiJt!Fs;TrustServerCertificate=true;"
  ShouldMigrate: "true"
