---
kind: Service
apiVersion: v1
metadata:
  name: movies-api-service
  namespace: movies
spec:
  selector:
    app: movies-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #NodePort
