apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: elk
  labels:
    app: logstash-logstash
spec:
  selector:
    app: logstash-logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
  type: ClusterIP
